# Generated by Django 5.0.2 on 2024-02-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='P1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('AP_JUICE', models.PositiveIntegerField(default=0)),
                ('AP_UBOT', models.PositiveIntegerField(default=0)),
                ('BUTY_JUICE', models.PositiveIntegerField(default=0)),
                ('BUTY_UBOT', models.PositiveIntegerField(default=0)),
                ('HL_JUICE', models.PositiveIntegerField(default=0)),
                ('HL_UBOT', models.PositiveIntegerField(default=0)),
                ('NS_JUICE', models.PositiveIntegerField(default=0)),
                ('NS_UBOT', models.PositiveIntegerField(default=0)),
                ('TRANS', models.PositiveIntegerField(default=0)),
                ('DAMAGE', models.PositiveIntegerField(default=0)),
                ('KONSOLA', models.PositiveIntegerField(default=0)),
                ('PS_CRET', models.PositiveIntegerField(default=0)),
                ('HANGERS', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
